name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Docker demone Start
        run: sudo service docker start 
      - name: Docker LogOut
        run: docker logout   
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t dhruvdarji123/nodejs-app .

      - name: Publish image to docker hub
        run: docker push dhruvdarji123/nodejs-app:latest
        
  deploy:
    needs: build
    #runs-on: [aws-ec2-node]
    runs-on: self-hosted
    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo ln -s /usr/bin/docker /usr/local/bin/docker
          sudo chmod 777 /var/run/docker.sock
      - name: Pull image from docker hub
        run: docker pull dhruvdarji123/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container dhruvdarji123/nodejs-app